from django.urls import path
from prop_6 import views
urlpatterns=[
    path('',views.index),
    path('login',views.login),
    path('register',views.register),
    path('petcare',views.petcare),
    path('vet',views.vet),
    path('admin_home',views.admin_home),
    path('add_cat',views.add_cat),
    path('ap_doc',views.ap_doc),
    path('apd_doc',views.apd_doc),
    path('ap_pet',views.ap_pet),
    path('apd_pet',views.apd_pet),
    path('app_pet',views.app_pet),
    path('app_doct',views.app_doct),
    path('user_home',views.user_home),
    path('add_pet',views.add_pet),
    path('v_doc',views.v_doc),
    path('v_pet',views.v_pet),
    path('v_petcare',views.v_petcare),
    path('gallery',views.gallery),
    path('petcare_home',views.petcare_home),
    path('vet_home',views.vet_home),
    path('add_breed',views.add_breed),
    path('cont',views.cont),
    path('cont2',views.cont2),
    path('req',views.req),
    path('v_details',views.v_details),
    path('vac',views.vac),
    path('book_vac',views. book_vac),
    path('v_req_vac',views. v_req_vac),
    path('app_vac',views. app_vac),
    path('apd_vac',views. apd_vac),
    path('conf_vac',views. conf_vac),
    path('conf_takecare',views.conf_takecare),
    path('v_req_takecare',views.v_req_takecare),
    path('app_takecare',views.app_takecare),
    path('cont_vet',views. cont_vet),
    path('comment',views. comment),
    path('comment2',views. comment2),
    path('vm',views. vm),
    path('trainer',views.trainer),
    path('ap_tra',views.ap_tra),
    path('apd_tra',views.apd_tra),
    path('app_tra',views.app_tra),
    path('trainer_home',views.trainer_home),
    path('add_spec',views.add_spec),
    path('v_com',views.v_com),
    path('vcom',views.vcom),
    path('tips',views.tips),
    path('v_tips',views.v_tips),
    path('user_tips',views.user_tips),
    path('user_tips_det',views.user_tips_det),
    path('tran',views.tran),
    path('petshop',views.petshop),
    path('ap_shop',views.ap_shop),
    path('apd_shop',views.apd_shop),
    path('app_shop',views.app_shop),
    path('shop_home',views.shop_home),
    path('ourpets',views.ourpets),
    path('ourpro',views.ourpro),
    path('addpets',views.addpets),
    path('addpro',views.addpro),
    path('addfeed',views.addfeed),
    path('ourfeed',views.ourfeed),
    path('v_feed',views.v_feed),
    path('v_p',views.v_p),
    path('v_pro',views.v_pro),
    path('buy_product',views.buy_product),
    path('feed',views.feed),
    path('petss',views.petss),
    path('pro',views.pro),
    path('v_feed_req',views.v_feed_req),
    path('v_toy_req',views.v_toy_req),
    path('v_pet_req',views.v_pet_req),
    path('user_db',views.user_db),
    path('my_qn',views.my_qn),
    path('bok',views.bok),
    path('bok1',views.bok1),
    path('post_bid',views.post_bid),
    path('ap_bid',views.ap_bid),
    path('approve',views.approve),
    path('sale_pet',views.sale_pet),
    path('m_bid',views.m_bid),
    path('o_bid',views.o_bid),
    path('bid',views.bid),
    path('bid_det',views.bid_det),
    path('bid_del',views.bid_del),
    path('b_pet',views.b_pet),
    path('b_pet1',views.b_pet1),
    path('o_ord',views.o_ord),
    path('pay',views.pay),
    
]
